### ISSUE TITLE
[Gedis Client] error when actor uses a schema not loaded in client side

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtecharchive/jumpscaleX_core#321] opened 2019-12-09 14:37 UTC
Gedis client and Gedis server both should have the same schemas.

StackTrace:
```
JSX> client2.actors.farms.list()                                                                         
Mon 09 10:10:10 ema/SchemaFactory.py -  96 - get_from_url                       : EXCEPTION: 
    Could not find schema with url:node.resource.price.1
--TRACEBACK------------------
/usr/local/lib/python3.6/dist-packages/ptpython/repl.py in _process_text
    84    self._execute(line)
/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py in patched_execute
    368    result_str = "%r\n" % (result,)
/sandbox/lib/jumpscale/Jumpscale/data/schema/JSXObject.py in __repr__
    287    return self._str_get(ansi=True)
/sandbox/var/codegen/schema_actors_tfgrid_directory_farms_list_3d0efcee0d2928d365b5e056f11b2e0c.py in _str_get
    195    items = j.data.types._types['list_6b2b117ca191d2243dec7e4c4d886343'].toHR(self.farms)
/sandbox/lib/jumpscale/Jumpscale/data/types/List.py in toHR
    252    return val2.pylist(subobj_format="H")
/sandbox/lib/jumpscale/Jumpscale/data/types/List.py in pylist
    138    res.append(item._ddict_hr)
/sandbox/lib/jumpscale/Jumpscale/data/schema/JSXObject.py in _ddict_hr
    252    d = self._ddict_hr_get(ansi=False)
/sandbox/var/codegen/schema_farm_1.py in _ddict_hr_get
    674    res = j.data.types._types['list_d247dd63efef6019cb1efdaab1e0de61'].toHR(self.resource_prices)
/sandbox/var/codegen/schema_farm_1.py in resource_prices
    327    v = j.data.types._types['list_d247dd63efef6019cb1efdaab1e0de61'].clean(self._capnp_obj_.resourcePrices)
/sandbox/lib/jumpscale/Jumpscale/data/types/List.py in clean
    295    item = ttype.clean(item)
/sandbox/lib/jumpscale/Jumpscale/data/types/JSXObjectTypeFactory.py in clean
    88    obj = j.data.serializers.jsxdata.loads(value, bcdb=bcdb)
/sandbox/lib/jumpscale/Jumpscale/data/serializers/SerializerJSXObject.py in loads
    67    schema_md5.url
/sandbox/lib/jumpscale/Jumpscale/data/schema/SchemaFactory.py in get_from_url
    96    raise j.exceptions.Input("Could not find schema with url:%s" % url)
-----------------------------

None
```
Loading models then trying same command
```
JSX> j.tools.threebot_packages.find()
JSX> client2 = j.clients.gedis.get(name="explorehamada", port=8901, host="explorer.testnet.grid.tf")     
JSX> client2.actors.farms.list()                                                                         
## actors.tfgrid.directory.farms.list.3d0efcee0d2928d365b5e056f11b2e0c
 - farms               :
    - threebot_id: 1    - iyo_organization: hamada    - name: test_farm     - wallet_addresses: ['test', 'test2']    - location: {'city': 'cairo', 'country': '', 'continent': '', 'latitude': '0', 'longitude': '0'}    - email: test@testmail.com    - resource_prices: [{'currency': 'EUR', 'cru': '346256', 'mru': '34667', 'hru': '346256', 'sru': '54674367', 'nru': '2345624'}]    - prefix_zero: ::/128    - id: 20    - threebot_id: 13,412    - iyo_organization: hamada    - name: waleed    - wallet_addresses: ['test', 'test2']    - location: {'city': 'cairo', 'country': '', 'continent': '', 'latitude': '0', 'longitude': '0'}    - email: test@testmail.com    - resource_prices: [{'currency': 'EUR', 'cru': '346256', 'mru': '34667', 'hru': '346256', 'sru': '54674367', 'nru': '2345624'}]    - prefix_zero: ::/128    - id: 21
```

**Comment by xmonader** [comment] 2019-12-10 13:38
duplicate of https://github.com/threefoldtech/jumpscaleX_core/issues/322

**Closed as completed by xmonader** 2019-12-10 13:38 UTC
Labels: type_bug, priority_critical
